#ifndef APP_EVENT_H_
#define APP_EVENT_H_

#include "ToCoNet_event.h"

typedef enum {
	E_EVENT_APP_BASE = ToCoNet_EVENT_APP_BASE,
	E_EVENT_CHSCAN_FINISH,
	E_EVENT_CHSCAN_FAIL,
	E_EVENT_MEASURE_FINISH,
	E_EVENT_MEASURE_FAIL,
	E_EVENT_TRANSMIT_FINISH,
	E_EVENT_TRANSMIT_FAIL,
	E_EVENT_REQUEST,
	E_EVENT_NFC_ACK,
	E_EVENT_NFC_RESPONSE
} teEventApp;


typedef enum {
	E_STATE_APP_BASE = ToCoNet_STATE_APP_BASE,
	E_STATE_INITIAL,
	E_STATE_CHSCAN_INIT,
	E_STATE_CHSCANNING,
	E_STATE_APP_SLEEP,
	E_STATE_TRANSMITTING,
	E_STATE_NFC_INIT,
	E_STATE_POLLING
} teStateApp;

#endif
